---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3 

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[sample-app-04292015::default]
    attributes:
